language: rust

services:
  - redis-server

before_install:
  - echo $TRAVIS_OS_NAME
  - set -e
  - . ./env && ./deps/install_packages.sh
  - sudo dpkg -i ./deps/emp-sh2pc/libcrypto++-dev*.deb
  - . ./env && make deps
  - redis-server --daemonize yes
  - redis-cli info
  - set +e

rust:
  - stable
  - nightly

script:
  - . ./env && cargo build --verbose --all 
  - . ./env && cargo test --verbose --all -- --nocapture
  - . ./env && cargo test --verbose --release --lib mpcwrapper -- --nocapture

matrix:
  allow_failures:
    - rust: nightly
