language: rust

services:
  - redis-server

before_install:
  - echo $TRAVIS_OS_NAME
  - set -e
  - . ./env && ./deps/install_packages.sh
  - sudo dpkg -i ./deps/emp-sh2pc/libcrypto++9v5*.deb
  - sudo dpkg -i ./deps/emp-sh2pc/libcrypto++-dev*.deb
  - . ./env && make deps
  - redis-server --daemonize yes
  - redis-cli info
  - echo -e "$PWD/deps/root/lib\n$PWD/target/release" | sudo tee /etc/ld.so.conf.d/libzkchannels.conf && sudo ldconfig
  - set +e

rust:
  - stable
  - nightly

script:
  - . ./env && cargo build --all 
  - . ./env && cargo test --all -- --nocapture
  - . ./env && cargo test --release --lib mpcwrapper -- --nocapture
  - . ./env && cargo test --release --lib channels_mpc -- --nocapture
  - . ./env && cargo test --release -- --ignored --nocapture
  - . ./env && ./test_gowrapper.sh

matrix:
  allow_failures:
    - rust: nightly
