[package]
name = "zkchannels"
version = "0.4.0"
authors = ["Bolt Labs, Inc <info@boltlabs.io>"]
description = "library implements zkChannels which was formerly Blind Off-chain Lightweight Transactions (BOLT)"
keywords = ["bitcoin", "zcash", "anonymous payment channels", "zkchannels"]
readme = "README.md"
homepage = "https://github.com/jakinyele/libzkchannels"
repository = "https://github.com/jakinyele/libzkchannels"
license = "MIT License"

[dependencies]
rand = "0.7"
ff_bl = { git = "https://github.com/boltlabs-inc/ff", branch = "master" }
pairing_bl = { git = "https://github.com/boltlabs-inc/pairing", branch = "master", features = ["serde"] }
libc = "*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = "1.0"
serde_bytes = "0.11.2"
time = "*"
# secp256k1 = { version = "0.15.0", features = ["rand", "serde"] }
secp256k1 = { git = "https://github.com/boltlabs-inc/rust-secp256k1", branch = "master", features = ["serde"] }
sha2 = { version = "0.8", default-features = false }
hex = "0.3.2"

[features]
mpc-bitcoin = []

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

