alias zkchannels-cust-open="zkchannels-cli open --party CUST --other-port 12347 --own-port 12346"
alias zkchannels-cust-init="zkchannels-cli init --party CUST --other-port 12347 --own-port 12346 --input-amount 0 --output-amount 30000000"
alias zkchannels-cust-activate="zkchannels-cli activate --party CUST --other-port 12347 --own-port 12346"
alias zkchannels-cust-unlink="zkchannels-cli unlink --party CUST --other-port 12347 --own-port 12346"
alias zkchannels-cust-pay="zkchannels-cli pay --party CUST --other-port 12347 --own-port 12346"
alias zkchannels-cust-close="zkchannels-cli close --party CUST --other-port 12347 --own-port 12346 --decompress-cust-close --file cust_close.json"

alias zkchannels-merch-open="zkchannels-cli open --party MERCH --own-port 12347 --other-port 12346"
alias zkchannels-merch-init="zkchannels-cli init --party MERCH --own-port 12347 --other-port 12346"
alias zkchannels-merch-activate="zkchannels-cli activate --party MERCH --own-port 12347 --other-port 12346"
alias zkchannels-merch-unlink="zkchannels-cli unlink --party MERCH --own-port 12347 --other-port 12346"
alias zkchannels-merch-pay="zkchannels-cli pay --party MERCH --own-port 12347 --other-port 12346 &"